services:

  # ================================
  # BASE DE DONNÉES MySQL
  # ================================
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql

  # ================================
  # CACHE Redis
  # ================================
  redis:
    image: redis:7-alpine

  # ================================
  # WORDPRESS (x2 replicas)
  # ================================
  wordpress:
    image: wordpress:6-apache
    depends_on:
      - mysql
      - redis
    environment:
      WORDPRESS_DB_HOST:     mysql:3306
      WORDPRESS_DB_NAME:     wordpress
      WORDPRESS_DB_USER:     wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_TIMEOUT', 1);
        define('WP_CACHE', true);
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 2


  # ================================
  # REVERSE PROXY nginx
  # ================================
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"     
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress

volumes:
  mysql_data:
  wordpress_data: